name: Go CI

# Run this workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger the workflow for changes in the backend folder
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger the workflow for PRs affecting the backend folder

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Specify the Go version you want to use

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        working-directory: ./backend  # Specify the backend folder
        run: go mod download

      # Run unit tests
      - name: Run tests
        working-directory: ./backend  # Specify the backend folder
        run: go test ./...

      # Optional: Display code coverage
      - name: Generate code coverage
        working-directory: ./backend  # Specify the backend folder
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: backend/coverage.out  # Ensure correct path to coverage file